### ISSUE TITLE
a greatful image!!  suggestion to run in the background

### ISSUE THREAD

**Issue by sorawa** [JasonRivers/Docker-nginx-rtmp#1]
if run 
docker run -p 1935:1935 -p 58080:8080 jasonrivers/nginx-rtmp

the terminal will block

**Comment by wbwangk** [comment]
docker run -d -p 1935:1935 -p 58080:8080 jasonrivers/nginx-rtmp

then it run in the backgound.

**Comment by JasonRivers** [comment]
Please use -d on docker run to run it in the background.
