### ISSUE TITLE
Nothing on stat page

### ISSUE THREAD

**Issue by chengdanhao** [JasonRivers/Docker-nginx-rtmp#3]
I run the docker with command `docker run –rm -it -h docker -p 80:8080 -p 1935:1935 jasonrivers/nginx-rtmp`

When I visit http://localhost/stat，it show a blank page without anything.

I read the nginx.conf, file `/opt/nginx/conf/stat.xsl` doesn't exist.

Anyone can tell me the reason?

**Comment by cam-smith** [comment]
right click->view source
it's a xml file, and by default chrome renders the xml as an empty page

**Comment by JasonRivers** [comment]
solution by @cam-smith
