### ISSUE TITLE
Getting a https stream

### ISSUE THREAD

**Issue by MartinHarran** [JasonRivers/Docker-nginx-rtmp#31]
I have this running fine in VLC, it can use both the rtmp and the hls streams. I can't, however, get it to stream onto a html video player. Going by some posts I've found on StackExchange, this seems to be because the browser expects a https source, not a http one. How to I modify the container to get this?

I'm running the container inside docker-compose file with jwilder/nginx-proxy and jrcs/letsencrypt-nginx-proxy-companion

**Comment by MartinHarran** [comment]
I got a workaround for this. In case anyone has the same problem, instead of trying to implement ssl into Jason’s container, I simply mounted the hls folder as a volume and also mounted it on the container running my http site which can now pull the stream from its own container.

**Comment by morya** [comment]
I run traefik in front of Docker-nginx-rtmp, which will handle all the SSL termination.

You can switch traefik into any proxy ( nginx, caddy, etc) to have ssl termination ability.
