### ISSUE TITLE
How to record

### ISSUE THREAD

**Issue by lupus721** [JasonRivers/Docker-nginx-rtmp#6]
How to record ,i can't set nginx.conf

**Comment by JasonRivers** [comment]
I'll be looking at this as part of the changes for #7 too - This way you'll be able to mount your own nginx.conf and the container won't try and write changes to it.

**Comment by JasonRivers** [comment]
From 8ae8cf3 you can mount your own nginx.conf file using:
-v /path/to/nginx.conf:/opt/nginx/conf/nginx.conf

If there is enough demand for recording as an option I'll add it to the default config depending on an environment variable.
